package com.exam.order.model;
// Generated Apr 24, 2019 4:40:17 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Bigcategory generated by hbm2java
 */
@Entity
@Table(name = "bigcategory", catalog = "onetech")
public class BigCategory implements java.io.Serializable {

	private Integer id;
	private String textDescription;
	private String htmlDescription;
	private byte[] image;
	private List<MenuCategory> menucategories = new ArrayList<MenuCategory>(0);
	private boolean emptyProduct;

	public BigCategory() {
	}

	public BigCategory(String textDescription, String htmlDescription, byte[] image, List<MenuCategory> menucategories) {
		this.textDescription = textDescription;
		this.htmlDescription = htmlDescription;
		this.image = image;
		this.menucategories = menucategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "textDescription", length = 4000)
	public String getTextDescription() {
		return this.textDescription;
	}

	public void setTextDescription(String textDescription) {
		this.textDescription = textDescription;
	}

	@Column(name = "htmlDescription", length = 16777215)
	public String getHtmlDescription() {
		return this.htmlDescription;
	}

	public void setHtmlDescription(String htmlDescription) {
		this.htmlDescription = htmlDescription;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "bigcategory")
	public List<MenuCategory> getMenucategories() {
		return this.menucategories;
	}

	public void setMenucategories(List<MenuCategory> menucategories) {
		this.menucategories = menucategories;
	}

	@Transient
	public boolean isEmptyProduct() {
		return emptyProduct;
	}

	public void setEmptyProduct(boolean emptyProduct) {
		this.emptyProduct = emptyProduct;
	}

}
