package com.exam.order.model;
// Generated Apr 24, 2019 4:40:17 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menucategory generated by hbm2java
 */
@Entity
@Table(name = "menucategory", catalog = "onetech")
public class MenuCategory implements java.io.Serializable {

	private Integer id;
	private BigCategory bigcategory;
	private String textDescription;
	private String htmlDescription;
	private byte[] image;
	private List<Product> products = new ArrayList<Product>(0);

	public MenuCategory() {
	}

	public MenuCategory(BigCategory bigcategory) {
		this.bigcategory = bigcategory;
	}

	public MenuCategory(BigCategory bigcategory, String textDescription, String htmlDescription, byte[] image,
			List<Product> products) {
		this.bigcategory = bigcategory;
		this.textDescription = textDescription;
		this.htmlDescription = htmlDescription;
		this.image = image;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bigCategoryId", nullable = false)
	public BigCategory getBigcategory() {
		return this.bigcategory;
	}

	public void setBigcategory(BigCategory bigcategory) {
		this.bigcategory = bigcategory;
	}

	@Column(name = "textDescription", length = 4000)
	public String getTextDescription() {
		return this.textDescription;
	}

	public void setTextDescription(String textDescription) {
		this.textDescription = textDescription;
	}

	@Column(name = "htmlDescription", length = 16777215)
	public String getHtmlDescription() {
		return this.htmlDescription;
	}

	public void setHtmlDescription(String htmlDescription) {
		this.htmlDescription = htmlDescription;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "menucategory")
	public List<Product> getProducts() {
		return this.products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
