package com.exam.order.model;
// Generated Apr 24, 2019 4:40:17 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "onetech")
public class Order implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private Date orderDate;
	private Date shippedDate;
	private String status;
	private String comments;
	private Integer sumPrice;
	private String couponCode;
	private List<OrderDetail> orderdetails = new ArrayList<OrderDetail>(0);

	public Order() {
	}

	public Order(Customer customer, Date orderDate, String status) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.status = status;
	}

	public Order(Customer customer, Date orderDate, Date shippedDate, String status, String comments, Integer sumPrice,
			String couponCode, List<OrderDetail> orderdetails) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.shippedDate = shippedDate;
		this.status = status;
		this.comments = comments;
		this.sumPrice = sumPrice;
		this.couponCode = couponCode;
		this.orderdetails = orderdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customerId", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "orderDate", nullable = false, length = 10)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "shippedDate", length = 10)
	public Date getShippedDate() {
		return this.shippedDate;
	}

	public void setShippedDate(Date shippedDate) {
		this.shippedDate = shippedDate;
	}

	@Column(name = "status", nullable = false, length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "comments", length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "sumPrice")
	public Integer getSumPrice() {
		return this.sumPrice;
	}

	public void setSumPrice(Integer sumPrice) {
		this.sumPrice = sumPrice;
	}

	@Column(name = "couponCode", length = 50)
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "order")
	public List<OrderDetail> getOrderdetails() {
		return this.orderdetails;
	}

	public void setOrderdetails(List<OrderDetail> orderdetails) {
		this.orderdetails = orderdetails;
	}

}
