package com.exam.order.model;
// Generated Apr 13, 2019 12:26:04 AM by Hibernate Tools 5.1.10.Final

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * User generated by hbm2java
 */
@Embeddable
public class ViewedId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1417509532651434350L;
	private Integer userId;
	private Integer productId;

	public ViewedId() {
	}

	public ViewedId(Integer userId, Integer productId) {
		super();
		this.userId = userId;
		this.productId = productId;
	}

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	// Getters omitted for brevity

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;

		if (o == null || getClass() != o.getClass())
			return false;

		ViewedId that = (ViewedId) o;
		return Objects.equals(userId, that.userId) && Objects.equals(productId, that.productId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(userId, productId);
	}
}
