package com.exam.order.model;
// Generated Apr 13, 2019 12:26:04 AM by Hibernate Tools 5.1.10.Final

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "viewed", catalog = "onetech")
public class Viewed implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6058552208799448817L;

	@EmbeddedId
	private ViewedId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@MapsId("userId")
	private User user;

	@ManyToOne(fetch = FetchType.LAZY)
	@MapsId("productId")
	private Product product;

	public Viewed() {
		super();
	}

	public Viewed(User user, Product product) {
		this.user = user;
		this.product = product;
		this.id = new ViewedId(user.getId(), product.getId());
	}

	// Getters and setters omitted for brevity

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;

		if (o == null || getClass() != o.getClass())
			return false;

		Viewed that = (Viewed) o;
		return Objects.equals(user, that.user) && Objects.equals(product, that.product);
	}

	@Override
	public int hashCode() {
		return Objects.hash(user, product);
	}
}
